# Generated by Django 3.2.4 on 2021-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pretencaoSalarial', models.IntegerField()),
                ('experiencia', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Ensino Medio'), ('3', 'Tecnólogo'), ('4', 'Ensino Superior'), ('5', 'Pós / MBA / Mestrado'), ('6', 'Doutorado')], max_length=1)),
            ],
        ),
    ]
