# Generated by Django 3.2.4 on 2021-06-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='name',
            new_name='nome',
        ),
    ]
