# Generated by Django 3.2.4 on 2021-06-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('requirements', models.TextField()),
                ('salaryRange', models.CharField(choices=[('1', 'ATÉ 1000,00'), ('2', 'DE 1000,01 ATÉ 2000,00'), ('3', 'DE 3000,01 ATÉ 3000,00'), ('4', 'ACIMA DE 3000,01')], max_length=1)),
                ('minimalEducationLevel', models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Ensino Medio'), ('3', 'Tecnólogo'), ('4', 'Ensino Superior'), ('5', 'Pós / MBA / Mestrado'), ('6', 'Doutorado')], max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
