# Generated by Django 3.2.4 on 2021-06-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_rename_name_candidato_nome'),
        ('vagas', '0002_vaga_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
        ),
        migrations.AddField(
            model_name='vaga',
            name='subscript',
            field=models.ManyToManyField(through='vagas.Candidatura', to='candidato.candidato'),
        ),
    ]
